[package]
name = "prompter"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus = { path = "/home/zeenix/checkout/dbus2/zbus/zbus", features = [
    "tokio",
], default-features = false }
tokio = { version = "1.44", features = ["full"] }
